version: "3.0"

services:
  qdirect-prod-postgres-consumer:
    image: postgis/postgis:12-master
    restart: on-failure
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=qdirect
      - PGPORT=5433
    volumes:
      - C:\qmanual\postgres\data\consumer:/var/lib/postgresql/data

  qdirect-prod-consumer-service:
    # Running on port 8081
    image: registry.gitlab.com/leon.panag/qmanuals-obsolete/q-direct-consumer-service:digipath-sprint-100
    restart: on-failure
    ports:
      - "8082:8081"
    volumes:
      - C:\qmanual\consumer-files:/files:rw
    depends_on:
      - qdirect-prod-postgres-consumer
    environment:
      - SERVER_PORT=8081
      - CORS_WHITELISTED_DOMAINS=http://localhost:3000,http://localhost:5000,https://qdirect.quantumar.com, https://134.209.194.28, http://172.89.60.32:8082, http://172.89.60.32:8082/auth/register, http://134.209.194.28:3000, http://192.168.1.105:3000, http://196.219.41.131:3000, https://196.219.41.131:3000, http://196.219.41.131, http://196.219.41.131:8082, http://10.0.0.108:3000, https://10.0.0.108:3000, http://10.0.0.108, https://10.0.0.108, http://172.28.160.1, https://172.28.160.1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://qdirect-prod-postgres-consumer:5433/qdirect
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_APPLICATION_NAME=qdirect-prod-consumer-service
      - LOGGING_FILE_NAME=/var/logs/qdirect-prod-consumer-service/qdirect-prod-consumer-service.log
      - COMPANY_UUID=ea3ba51d-239e-4d73-b6dd-2299805dd4c6

  qdirect-prod-consumer-frontend:
    # Running on port 5000
    image: registry.gitlab.com/leon.panag/qmanuals-obsolete/q-direct-consumer-frontend:digipath-sprint-100
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - BACKEND_BASE_URL=http://172.28.160.1:8082/
      - FRONTEND_BASE_PATH=
      - COMPANY_UUID=ea3ba51d-239e-4d73-b6dd-2299805dd4c6
